name: Deploy to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Upload frontend to server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r frontend/dist/* $SERVER_USER@$SERVER_IP:/var/www/$REPO_NAME/frontend/dist/

      - name: Pull latest code and restart backend
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_IP << EOF
            cd /var/www/$REPO_NAME
            git pull origin develop
            cd backend
            npm install
            pm2 restart burn-black-server
          EOF
